services:
  db:
    restart: unless-stopped
    # In production, the database doesn't need to bind a port to the host (unless connecting directly to the DB in prod)
    ports: !reset []
  api:
    build:
      target: prod
    # In production, we don't need to mount the host project directory for hot reloading
    volumes: !reset []
    restart: unless-stopped
    # TODO: add scaling directives
  # load-balancer:
  #   image: traefik