// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: customers.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const addCustomer = `-- name: AddCustomer :execresult
INSERT INTO customers (
    username,
    password_hash,
    first_name,
    last_name,
    email,
    birth_day,
    phone_number,
    address
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type AddCustomerParams struct {
	Username     string `json:"username"`
	PasswordHash []byte `json:"-"`
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	Email        string `json:"email"`
	BirthDay     string `json:"birth_day"`
	PhoneNumber  string `json:"phone_number"`
	Address      string `json:"address"`
}

func (q *Queries) AddCustomer(ctx context.Context, arg AddCustomerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addCustomer,
		arg.Username,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.BirthDay,
		arg.PhoneNumber,
		arg.Address,
	)
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT customer_id, username, password_hash, first_name, last_name, email, birth_day, phone_number, address, created_at, updated_at FROM customers
WHERE customer_id = ?
`

func (q *Queries) GetCustomerByID(ctx context.Context, customerID int32) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByID, customerID)
	var i Customer
	err := row.Scan(
		&i.CustomerID,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.BirthDay,
		&i.PhoneNumber,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByToken = `-- name: GetCustomerByToken :one
SELECT c.customer_id, c.username, c.password_hash, c.first_name, c.last_name, c.email, c.birth_day, c.phone_number, c.address, c.created_at, c.updated_at
FROM customers AS c
INNER JOIN tokens AS t
    ON c.customer_id = t.customer_id
    -- TODO: might replace the expiry comparison with the internal ` + "`" + `> NOW()` + "`" + `
WHERE t.token_hash = ? AND t.token_scope = ? AND t.expiry > ?
`

type GetCustomerByTokenParams struct {
	TokenHash  []byte    `json:"-"`
	TokenScope string    `json:"-"`
	Date       time.Time `json:"date"`
}

func (q *Queries) GetCustomerByToken(ctx context.Context, arg GetCustomerByTokenParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByToken, arg.TokenHash, arg.TokenScope, arg.Date)
	var i Customer
	err := row.Scan(
		&i.CustomerID,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.BirthDay,
		&i.PhoneNumber,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByUsername = `-- name: GetCustomerByUsername :one
SELECT customer_id, username, password_hash, first_name, last_name, email, birth_day, phone_number, address, created_at, updated_at FROM customers
WHERE username = ?
`

func (q *Queries) GetCustomerByUsername(ctx context.Context, username string) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByUsername, username)
	var i Customer
	err := row.Scan(
		&i.CustomerID,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.BirthDay,
		&i.PhoneNumber,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
