// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type OrdersOrderStatus string

const (
	OrdersOrderStatusPending    OrdersOrderStatus = "pending"
	OrdersOrderStatusProcessing OrdersOrderStatus = "processing"
	OrdersOrderStatusShipped    OrdersOrderStatus = "shipped"
	OrdersOrderStatusDelivered  OrdersOrderStatus = "delivered"
	OrdersOrderStatusCancelled  OrdersOrderStatus = "cancelled"
)

func (e *OrdersOrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrdersOrderStatus(s)
	case string:
		*e = OrdersOrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrdersOrderStatus: %T", src)
	}
	return nil
}

type NullOrdersOrderStatus struct {
	OrdersOrderStatus OrdersOrderStatus
	Valid             bool // Valid is true if OrdersOrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrdersOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrdersOrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrdersOrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrdersOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrdersOrderStatus), nil
}

type Cart struct {
	CartID     int32
	CustomerID sql.NullInt32
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type CartItem struct {
	CartID    sql.NullInt32
	ProductID sql.NullInt32
	Quantity  int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Customer struct {
	CustomerID  int32
	FirstName   string
	LastName    string
	Email       string
	BirthDay    time.Time
	PhoneNumber string
	Address     string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Order struct {
	OrderID     int32
	CustomerID  sql.NullInt32
	OrderStatus OrdersOrderStatus
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	OrderTotal  string
}

type OrderItem struct {
	OrderID            sql.NullInt32
	ProductID          sql.NullInt32
	Quantity           int32
	ProductPriceAtTime string
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
}

type Product struct {
	ProductID          int32
	Title              string
	ProductDescription string
	Category           sql.NullInt32
	Price              string
	ImageUrl           string
	StockQuantity      int32
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
}

type ProductCategory struct {
	CategoryID          int32
	CategoryName        string
	CategoryDescription sql.NullString
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
}
