// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type OrdersOrderStatus string

const (
	OrdersOrderStatusPending    OrdersOrderStatus = "pending"
	OrdersOrderStatusProcessing OrdersOrderStatus = "processing"
	OrdersOrderStatusShipped    OrdersOrderStatus = "shipped"
	OrdersOrderStatusDelivered  OrdersOrderStatus = "delivered"
	OrdersOrderStatusCancelled  OrdersOrderStatus = "cancelled"
)

func (e *OrdersOrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrdersOrderStatus(s)
	case string:
		*e = OrdersOrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrdersOrderStatus: %T", src)
	}
	return nil
}

type NullOrdersOrderStatus struct {
	OrdersOrderStatus OrdersOrderStatus `json:"orders_order_status"`
	Valid             bool              `json:"valid"` // Valid is true if OrdersOrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrdersOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrdersOrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrdersOrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrdersOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrdersOrderStatus), nil
}

type Cart struct {
	CartID     int32         `json:"cart_id"`
	CustomerID sql.NullInt32 `json:"customer_id"`
	CreatedAt  time.Time     `json:"created_at"`
	UpdatedAt  time.Time     `json:"updated_at"`
}

type CartItem struct {
	CartID    sql.NullInt32 `json:"cart_id"`
	ProductID sql.NullInt32 `json:"product_id"`
	Quantity  int32         `json:"quantity"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type Customer struct {
	CustomerID   int32     `json:"customer_id"`
	Username     string    `json:"username"`
	PasswordHash []byte    `json:"-"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	Email        string    `json:"email"`
	BirthDay     string    `json:"birth_day"`
	PhoneNumber  string    `json:"phone_number"`
	Address      string    `json:"address"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Order struct {
	OrderID     int32             `json:"order_id"`
	CustomerID  sql.NullInt32     `json:"customer_id"`
	OrderStatus OrdersOrderStatus `json:"order_status"`
	CreatedAt   time.Time         `json:"created_at"`
	UpdatedAt   time.Time         `json:"updated_at"`
	OrderTotal  string            `json:"order_total"`
}

type OrderItem struct {
	OrderID            sql.NullInt32 `json:"order_id"`
	ProductID          sql.NullInt32 `json:"product_id"`
	Quantity           int32         `json:"quantity"`
	ProductPriceAtTime string        `json:"product_price_at_time"`
	CreatedAt          time.Time     `json:"created_at"`
	UpdatedAt          time.Time     `json:"updated_at"`
}

type Product struct {
	ProductID          int32         `json:"product_id"`
	Title              string        `json:"title"`
	ProductDescription string        `json:"product_description"`
	Category           sql.NullInt32 `json:"category"`
	Price              string        `json:"price"`
	ImageUrl           string        `json:"image_url"`
	StockQuantity      int32         `json:"stock_quantity"`
	CreatedAt          time.Time     `json:"created_at"`
	UpdatedAt          time.Time     `json:"updated_at"`
}

type ProductCategory struct {
	CategoryID          int32     `json:"category_id"`
	CategoryName        string    `json:"category_name"`
	CategoryDescription string    `json:"category_description"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}
