// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: product_categories.sql

package repository

import (
	"context"
)

const getProductCategory = `-- name: GetProductCategory :one
SELECT category_id, category_name, category_description, created_at, updated_at FROM product_categories
WHERE category_id = ?
LIMIT 1
`

func (q *Queries) GetProductCategory(ctx context.Context, categoryID int32) (ProductCategory, error) {
	row := q.db.QueryRowContext(ctx, getProductCategory, categoryID)
	var i ProductCategory
	err := row.Scan(
		&i.CategoryID,
		&i.CategoryName,
		&i.CategoryDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
