// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: product_categories.sql

package repository

import (
	"context"
	"database/sql"
)

const addProductCategory = `-- name: AddProductCategory :execresult
INSERT INTO product_categories (
    category_name, category_description
) VALUES (?, ?)
`

type AddProductCategoryParams struct {
	CategoryName        string `json:"category_name"`
	CategoryDescription string `json:"category_description"`
}

func (q *Queries) AddProductCategory(ctx context.Context, arg AddProductCategoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addProductCategory, arg.CategoryName, arg.CategoryDescription)
}

const getAllProductCategories = `-- name: GetAllProductCategories :many
SELECT category_id, category_name, category_description, created_at, updated_at FROM product_categories
`

func (q *Queries) GetAllProductCategories(ctx context.Context) ([]ProductCategory, error) {
	rows, err := q.db.QueryContext(ctx, getAllProductCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductCategory
	for rows.Next() {
		var i ProductCategory
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductCategory = `-- name: GetProductCategory :one
SELECT category_id, category_name, category_description, created_at, updated_at FROM product_categories
WHERE category_id = ?
LIMIT 1
`

func (q *Queries) GetProductCategory(ctx context.Context, categoryID int32) (ProductCategory, error) {
	row := q.db.QueryRowContext(ctx, getProductCategory, categoryID)
	var i ProductCategory
	err := row.Scan(
		&i.CategoryID,
		&i.CategoryName,
		&i.CategoryDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
