// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package repository

import (
	"context"
	"database/sql"
)

const addProduct = `-- name: AddProduct :execresult
INSERT INTO products (
    title, product_description, category, price, image_url, stock_quantity
) VALUES (?, ?, ?, ?, ?, ?)
`

type AddProductParams struct {
	Title              string
	ProductDescription string
	Category           sql.NullInt32
	Price              string
	ImageUrl           string
	StockQuantity      int32
}

func (q *Queries) AddProduct(ctx context.Context, arg AddProductParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addProduct,
		arg.Title,
		arg.ProductDescription,
		arg.Category,
		arg.Price,
		arg.ImageUrl,
		arg.StockQuantity,
	)
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE product_id = ?
`

func (q *Queries) DeleteProduct(ctx context.Context, productID int32) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, productID)
	return err
}

const editProduct = `-- name: EditProduct :execresult
UPDATE products
SET
    title = ?,
    product_description = ?,
    category = ?,
    price = ?,
    image_url = ?,
    stock_quantity = ?
WHERE product_id = ?
`

type EditProductParams struct {
	Title              string
	ProductDescription string
	Category           sql.NullInt32
	Price              string
	ImageUrl           string
	StockQuantity      int32
	ProductID          int32
}

func (q *Queries) EditProduct(ctx context.Context, arg EditProductParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, editProduct,
		arg.Title,
		arg.ProductDescription,
		arg.Category,
		arg.Price,
		arg.ImageUrl,
		arg.StockQuantity,
		arg.ProductID,
	)
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT product_id, title, product_description, category, price, image_url, stock_quantity, created_at, updated_at FROM products
`

func (q *Queries) GetAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ProductID,
			&i.Title,
			&i.ProductDescription,
			&i.Category,
			&i.Price,
			&i.ImageUrl,
			&i.StockQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProduct = `-- name: GetProduct :one
SELECT product_id, title, product_description, category, price, image_url, stock_quantity, created_at, updated_at FROM products
WHERE product_id = ?
LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, productID int32) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, productID)
	var i Product
	err := row.Scan(
		&i.ProductID,
		&i.Title,
		&i.ProductDescription,
		&i.Category,
		&i.Price,
		&i.ImageUrl,
		&i.StockQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
