// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package repository

import (
	"context"
	"database/sql"
)

const addProduct = `-- name: AddProduct :execresult
INSERT INTO products (
    title, product_description, category, price, image_url, stock_quantity
) VALUES (?, ?, ?, ?, ?, ?)
`

type AddProductParams struct {
	Title              string        `json:"title"`
	ProductDescription string        `json:"product_description"`
	Category           sql.NullInt32 `json:"category"`
	Price              string        `json:"price"`
	ImageUrl           string        `json:"image_url"`
	StockQuantity      int32         `json:"stock_quantity"`
}

func (q *Queries) AddProduct(ctx context.Context, arg AddProductParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addProduct,
		arg.Title,
		arg.ProductDescription,
		arg.Category,
		arg.Price,
		arg.ImageUrl,
		arg.StockQuantity,
	)
}

const deleteProduct = `-- name: DeleteProduct :execresult
DELETE FROM products
WHERE product_id = ?
`

func (q *Queries) DeleteProduct(ctx context.Context, productID int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteProduct, productID)
}

const editProduct = `-- name: EditProduct :execresult
UPDATE products
SET
    title = COALESCE(?, title),
    product_description
    = COALESCE(?, product_description),
    category = COALESCE(?, category),
    price = COALESCE(?, price),
    image_url = COALESCE(?, image_url),
    stock_quantity = COALESCE(?, stock_quantity)
WHERE product_id = ?
`

type EditProductParams struct {
	Title              sql.NullString `json:"title"`
	ProductDescription sql.NullString `json:"product_description"`
	Category           sql.NullInt32  `json:"category"`
	Price              sql.NullString `json:"price"`
	ImageUrl           sql.NullString `json:"image_url"`
	StockQuantity      sql.NullInt32  `json:"stock_quantity"`
	ProductID          int32          `json:"product_id"`
}

func (q *Queries) EditProduct(ctx context.Context, arg EditProductParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, editProduct,
		arg.Title,
		arg.ProductDescription,
		arg.Category,
		arg.Price,
		arg.ImageUrl,
		arg.StockQuantity,
		arg.ProductID,
	)
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT product_id, title, product_description, category, price, image_url, stock_quantity, created_at, updated_at FROM products
`

func (q *Queries) GetAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ProductID,
			&i.Title,
			&i.ProductDescription,
			&i.Category,
			&i.Price,
			&i.ImageUrl,
			&i.StockQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestProducts = `-- name: GetLatestProducts :many
SELECT product_id, title, product_description, category, price, image_url, stock_quantity, created_at, updated_at FROM products
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) GetLatestProducts(ctx context.Context, limit int32) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getLatestProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ProductID,
			&i.Title,
			&i.ProductDescription,
			&i.Category,
			&i.Price,
			&i.ImageUrl,
			&i.StockQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProduct = `-- name: GetProduct :one
SELECT product_id, title, product_description, category, price, image_url, stock_quantity, created_at, updated_at FROM products
WHERE product_id = ?
LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, productID int32) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, productID)
	var i Product
	err := row.Scan(
		&i.ProductID,
		&i.Title,
		&i.ProductDescription,
		&i.Category,
		&i.Price,
		&i.ImageUrl,
		&i.StockQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
