// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package repository

import (
	"context"
	"database/sql"
)

const addProduct = `-- name: AddProduct :execresult
INSERT INTO products (
    title, product_description, category, price, image_url, stock_quantity
) VALUES (?, ?, ?, ?, ?, ?)
`

type AddProductParams struct {
	Title              string `json:"title"`
	ProductDescription string `json:"product_description"`
	Category           int32  `json:"category"`
	Price              string `json:"price"`
	ImageUrl           string `json:"image_url"`
	StockQuantity      int32  `json:"stock_quantity"`
}

func (q *Queries) AddProduct(ctx context.Context, arg AddProductParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addProduct,
		arg.Title,
		arg.ProductDescription,
		arg.Category,
		arg.Price,
		arg.ImageUrl,
		arg.StockQuantity,
	)
}

const deleteProduct = `-- name: DeleteProduct :execresult
DELETE FROM products
WHERE product_id = ?
`

func (q *Queries) DeleteProduct(ctx context.Context, productID int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteProduct, productID)
}

const editProduct = `-- name: EditProduct :execresult
UPDATE products
SET
    title = COALESCE(?, title),
    product_description
    = COALESCE(?, product_description),
    category = COALESCE(?, category),
    price = COALESCE(?, price),
    image_url = COALESCE(?, image_url),
    stock_quantity = COALESCE(?, stock_quantity)
WHERE product_id = ?
`

type EditProductParams struct {
	Title              sql.NullString `json:"title"`
	ProductDescription sql.NullString `json:"product_description"`
	Category           sql.NullInt32  `json:"category"`
	Price              sql.NullString `json:"price"`
	ImageUrl           sql.NullString `json:"image_url"`
	StockQuantity      sql.NullInt32  `json:"stock_quantity"`
	ProductID          int32          `json:"product_id"`
}

func (q *Queries) EditProduct(ctx context.Context, arg EditProductParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, editProduct,
		arg.Title,
		arg.ProductDescription,
		arg.Category,
		arg.Price,
		arg.ImageUrl,
		arg.StockQuantity,
		arg.ProductID,
	)
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT product_id, title, product_description, category, price, image_url, stock_quantity, created_at, updated_at FROM products_with_category
`

func (q *Queries) GetAllProducts(ctx context.Context) ([]ProductsWithCategory, error) {
	rows, err := q.db.QueryContext(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductsWithCategory
	for rows.Next() {
		var i ProductsWithCategory
		if err := rows.Scan(
			&i.ProductID,
			&i.Title,
			&i.ProductDescription,
			&i.Category,
			&i.Price,
			&i.ImageUrl,
			&i.StockQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestProducts = `-- name: GetLatestProducts :many
SELECT p.product_id, p.title, p.product_description, p.category, p.price, p.image_url, p.stock_quantity, p.created_at, p.updated_at
FROM products_with_category AS p
WHERE (
    SELECT COUNT(*)
    FROM products_with_category AS p2
    WHERE
        p2.category = p.category
        AND (
            p2.created_at > p.created_at
            OR (p2.created_at = p.created_at AND p2.product_id > p.product_id)
        )
) < CAST(? AS SIGNED)
ORDER BY p.category ASC, p.created_at DESC, p.product_id DESC
`

func (q *Queries) GetLatestProducts(ctx context.Context, categoryLimit int64) ([]ProductsWithCategory, error) {
	rows, err := q.db.QueryContext(ctx, getLatestProducts, categoryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductsWithCategory
	for rows.Next() {
		var i ProductsWithCategory
		if err := rows.Scan(
			&i.ProductID,
			&i.Title,
			&i.ProductDescription,
			&i.Category,
			&i.Price,
			&i.ImageUrl,
			&i.StockQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProduct = `-- name: GetProduct :one
SELECT product_id, title, product_description, category, price, image_url, stock_quantity, created_at, updated_at FROM products_with_category
WHERE product_id = ?
`

func (q *Queries) GetProduct(ctx context.Context, productID int32) (ProductsWithCategory, error) {
	row := q.db.QueryRowContext(ctx, getProduct, productID)
	var i ProductsWithCategory
	err := row.Scan(
		&i.ProductID,
		&i.Title,
		&i.ProductDescription,
		&i.Category,
		&i.Price,
		&i.ImageUrl,
		&i.StockQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
