// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tokens.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const addToken = `-- name: AddToken :execresult
INSERT INTO tokens (
    token_hash,
    customer_id,
    expiry,
    token_scope
) VALUES (?, ?, ?, ?)
`

type AddTokenParams struct {
	TokenHash  []byte    `json:"-"`
	CustomerID int32     `json:"-"`
	Expiry     time.Time `json:"expiry"`
	TokenScope string    `json:"-"`
}

func (q *Queries) AddToken(ctx context.Context, arg AddTokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addToken,
		arg.TokenHash,
		arg.CustomerID,
		arg.Expiry,
		arg.TokenScope,
	)
}
